/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Makanan;

import FactoryDAO.FactoryDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author agasigp
 */
public class MakananView extends javax.swing.JFrame {

    private List<Makanan> listMakanan;
    private final String[] tbHeader;
    
    private DefaultTableModel tabelModel;
    private boolean updSQLFlag = false;
    private int baris;
    
    FactoryDAO factoryDAO = new FactoryDAO();
    MakananInterface makananInterface = factoryDAO.getMakananDAO();
    
    /**
     * Creates new form MakananView
     */
    public MakananView() {
        initComponents();
        
        tbHeader = new String[]{"ID", "NAMA", "TIPE", "STATUS", "KETERANGAN", "HARGA", "CREATED AT", "UPDATED AT"};
        tabelModel = new DefaultTableModel(null, tbHeader);
        tabelMakanan.setModel(tabelModel);
        addMakananItem();
        tampilMakanan();
    }

    private void tampilMakanan() {
        MakananImplement makananImplement = new MakananImplement();
        listMakanan = makananImplement.tampilMakanan();
        tabelModel = (DefaultTableModel) tabelMakanan.getModel();
        tabelModel.setRowCount(0);
        
        for (Makanan dataMakanan : listMakanan) {
            tabelModel.addRow(new Object[]{dataMakanan.getId(), dataMakanan.getNama(), getTipe(dataMakanan.getTipe()), getStatus(dataMakanan.getStatus()), dataMakanan.getKeterangan(), dataMakanan.getHarga()});
        }
        
        int ambilBaris = tabelMakanan.getRowCount();
        
        if (ambilBaris > 0) {
            tabelMakanan.addRowSelectionInterval(0, 0);
        }
    }
    
    private void addMakananItem() {
        cmbTipe.addItem(new MakananTipeItem("MKN", "Makanan"));
        cmbTipe.addItem(new MakananTipeItem("MMN", "Minuman"));
        cmbTipe.addItem(new MakananTipeItem("LK", "Lauk"));
    }
    
    private String getStatus(int status) {
        if (status == 1) {
            return "Ada";
        } else {
            return "Habis";
        }
    }
    
    private String getTipe(String tipe) {
        switch (tipe) {
            case "MKN":
                return "Makanan";
            case "MMN":
                return "Minuman";
            default:
                return "Lauk";
        }
    }
    
    private void clearForm() {
        txtNama.setText("");
        txtHarga.setText("");
        txtKeterangan.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSimpan = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMakanan = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        cmbTipe = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtKeterangan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnClear.setText("Kosongkan");

        tabelMakanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama", "Harga", "Keterangan", "Dibuat", "Diupdate"
            }
        ));
        jScrollPane1.setViewportView(tabelMakanan);

        btnHapus.setText("Hapus");

        cmbTipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipeActionPerformed(evt);
            }
        });

        jLabel1.setText("Nama");

        jLabel2.setText("Harga");

        jLabel3.setText("Tipe");

        jLabel4.setText("Keterangan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNama)
                                    .addComponent(txtHarga)
                                    .addComponent(txtKeterangan)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbTipe, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClear)
                                .addGap(82, 82, 82)))
                        .addGap(504, 504, 504))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbTipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnClear)
                    .addComponent(btnHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        Makanan makanan = new Makanan();
        MakananTipeItem tipeMakananModel = (MakananTipeItem) cmbTipe.getSelectedItem();
        
        String namaMakanan = txtNama.getText();
        String tipeMakanan = tipeMakananModel.getKey();
        int hargaMakanan = Integer.parseInt(txtHarga.getText());
        String keteranganMakanan = txtKeterangan.getText();
        
        makanan.setNama(namaMakanan);
        makanan.setTipe(tipeMakanan);
        makanan.setHarga(hargaMakanan);
        makanan.setKeterangan(keteranganMakanan);
        
        if (updSQLFlag == false) {
            if (txtNama.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Nama harus diisi!", "Peringatan", JOptionPane.ERROR_MESSAGE);
                txtNama.grabFocus();
            } else if (txtHarga.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Harga harus diisi!", "Peringatan", JOptionPane.ERROR_MESSAGE);
                txtHarga.grabFocus();
            } else {
                makananInterface.simpanMakanan(makanan);
//                JOptionPane.showMessageDialog(null, "", "Info", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        tampilMakanan();
        clearForm();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void cmbTipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipeActionPerformed
        // TODO add your handling code here:
//        System.out.println(cmbTipe.getModel().getSelectedItem().);
    }//GEN-LAST:event_cmbTipeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox cmbTipe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelMakanan;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKeterangan;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
