/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transaksi;

import FactoryDAO.FactoryDAO;
import Helper.UserSession;
import Login.LoginView;
import Makanan.Makanan;
import Makanan.MakananImplement;
import Makanan.MakananView;
import User.UserView;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author agasigp
 */
public class TransaksiView extends javax.swing.JFrame {
    private List<Makanan> listMakanan;
    private ArrayList<TransaksiDetail> listDetailTransaksi;
    private DefaultTableModel tabelModel;
    private String[] tbHeader;
    private int total = 0;
    
    FactoryDAO factoryDao = new FactoryDAO();
    TransaksiInterface transaksiInterface = factoryDao.getTransaksiDAO();
    private boolean updSQLFlag;
            
    /**
     * Creates new form Main
     */
    public TransaksiView() {
        initComponents();
        initNoTransaksi();
        
        addMakananItem("MKN");
        addMakananItem("MMN");
        addMakananItem("LK");
        
        initTable();
        
        lblUsername.setText(UserSession.getUsername());
        lblTanggal.setText(new SimpleDateFormat("dd-MM-yyyy").format(Calendar.getInstance().getTime()));
    }
    
    private void initNoTransaksi() {
        TransaksiImplement transaksi = new TransaksiImplement();
        
        if (transaksi.countTransaksi() < 9) {
            txtNoTransaksi.setText("00" + Integer.toString(transaksi.countTransaksi() + 1));
        } else if (transaksi.countTransaksi() <= 99) {
            txtNoTransaksi.setText("0" + Integer.toString(transaksi.countTransaksi() + 1));
        } else {
            txtNoTransaksi.setText(Integer.toString(transaksi.countTransaksi() + 1));
        }
    }
    
    private void initTable() {
        tbHeader = new String[]{"ITEM ID", "NAMA", "HARGA", "HARGA", "JUMLAH"};
        tabelModel = new DefaultTableModel(null, tbHeader);
        tblTransaksi.setModel(tabelModel);
    }
    
    private void sumTotal(int subTotal) {
        total = total + subTotal;
        txtTotal.setText(Integer.toString(total));
    }
    
    private void addMakananItem(String tipe) {
        MakananImplement makananImplement = new MakananImplement();
        listMakanan = makananImplement.tampilMakanan(tipe);
        
        for (Makanan dataMakanan : listMakanan) {
            switch (dataMakanan.getTipe()) {
                case "MKN":
                    cmbMakanan.addItem(new Makanan(dataMakanan.getId(), dataMakanan.getNama(), dataMakanan.getHarga()));
                    break;
                case "MMN":
                    cmbMinuman.addItem(new Makanan(dataMakanan.getId(), dataMakanan.getNama(), dataMakanan.getHarga()));
                    break;
                default:
                    cmbLauk.addItem(new Makanan(dataMakanan.getId(), dataMakanan.getNama(), dataMakanan.getHarga()));
                    break;
            }
        }
    }
    
    private void clearForm() {
        initTable();
        txtTotal.setText("0");
        txtBayar.setText("0");
        txtKembali.setText("0");
        
        spnMakanan.setValue(0);
        spnMinuman.setValue(0);
        spnLauk.setValue(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        cmbMakanan = new javax.swing.JComboBox();
        spnMakanan = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        cmbMinuman = new javax.swing.JComboBox();
        spnMinuman = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        spnLauk = new javax.swing.JSpinner();
        cmbLauk = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnTambahMinuman = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtNoTransaksi = new javax.swing.JTextField();
        lblTanggal = new javax.swing.JLabel();
        btnTambahLauk = new javax.swing.JButton();
        btnTambahMakanan = new javax.swing.JButton();
        NumberFormat format = NumberFormat.getInstance();
        format.setGroupingUsed(false);
        NumberFormatter formatter = new NumberFormatter(format);
        formatter.setValueClass(Integer.class);
        formatter.setMinimum(0);
        formatter.setMaximum(Integer.MAX_VALUE);
        formatter.setAllowsInvalid(false);
        txtBayar = new javax.swing.JFormattedTextField(formatter);
        txtKembali = new javax.swing.JFormattedTextField(formatter);
        txtTotal = new javax.swing.JFormattedTextField(formatter);
        btnBayar = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jMenu6.setText("File");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar2.add(jMenu7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Makanan");

        spnMakanan.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel2.setText("Minuman");

        spnMinuman.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel3.setText("Lauk");

        spnLauk.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel4.setText("Daftar Beli");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnTambahMinuman.setText("Tambah");
        btnTambahMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahMinumanActionPerformed(evt);
            }
        });

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEM ID", "ITEM", "HARGA", "JUMLAH", "SUB TOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblTransaksi);

        jLabel5.setText("Total");

        jLabel6.setText("Bayar");

        jLabel7.setText("Kembali");

        btnClear.setText("Kosongkan");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel8.setText("No Transaksi");

        txtNoTransaksi.setEditable(false);

        lblTanggal.setText("Tanggal");

        btnTambahLauk.setText("Tambah");
        btnTambahLauk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahLaukActionPerformed(evt);
            }
        });

        btnTambahMakanan.setText("Tambah");
        btnTambahMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahMakananActionPerformed(evt);
            }
        });

        txtBayar.setText("0");

        txtKembali.setEditable(false);
        txtKembali.setText("0");

        txtTotal.setEditable(false);
        txtTotal.setText("0");

        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        lblUsername.setText("Username");

        jMenu2.setText("Menu");

        jMenuItem1.setText("Laporan");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Logout");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu8.setText("Master");

        jMenuItem3.setText("Makanan");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem3);

        jMenuItem4.setText("User");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem4);

        jMenuBar1.add(jMenu8);

        jMenu3.setText("About");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHapus)
                                .addGap(18, 18, 18)
                                .addComponent(btnClear)
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBayar)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel6)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(49, 49, 49)
                                            .addComponent(txtKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtNoTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(316, 316, 316))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spnMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(btnTambahMakanan))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel1))))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(spnMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(btnTambahMinuman)))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(btnTambahLauk))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbLauk, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(spnLauk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel3))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(lblUsername)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNoTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername)
                    .addComponent(lblTanggal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbLauk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnLauk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahMinuman)
                    .addComponent(btnTambahLauk)
                    .addComponent(btnTambahMakanan))
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan)
                    .addComponent(btnClear)
                    .addComponent(btnHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBayar)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        dispose();
        new LoginView().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        MakananView makananView = new MakananView();
        makananView.setVisible(true);
        makananView.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        UserView userView = new UserView();
        userView.setVisible(true);
        userView.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
//        System.out.println("fhslhdflds");
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void btnTambahMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahMinumanActionPerformed
        Makanan tipeMakananModel = (Makanan) cmbMinuman.getSelectedItem();
        
        TransaksiDetail transaksiDetail = new TransaksiDetail();
        transaksiDetail.setMakananId(tipeMakananModel.getId());
        transaksiDetail.setJumlah(Integer.parseInt(spnMinuman.getValue().toString()));
        
        listDetailTransaksi = new ArrayList<>();
        listDetailTransaksi.add(transaksiDetail);
        
        tabelModel = (DefaultTableModel) tblTransaksi.getModel();
        tabelModel.addRow(new Object[]{transaksiDetail.getMakananId(),
            tipeMakananModel.getNama(),
            tipeMakananModel.getHarga(),
            transaksiDetail.getJumlah(),
            tipeMakananModel.getHarga() * transaksiDetail.getJumlah()
        });
        
        sumTotal(tipeMakananModel.getHarga() * transaksiDetail.getJumlah());
    }//GEN-LAST:event_btnTambahMinumanActionPerformed

    private void btnTambahLaukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahLaukActionPerformed
        // TODO add your handling code here:
        Makanan tipeMakananModel = (Makanan) cmbLauk.getSelectedItem();
        
        TransaksiDetail transaksiDetail = new TransaksiDetail();
        transaksiDetail.setMakananId(tipeMakananModel.getId());
        transaksiDetail.setJumlah(Integer.parseInt(spnLauk.getValue().toString()));
        
        listDetailTransaksi = new ArrayList<>();
        listDetailTransaksi.add(transaksiDetail);
        
        tabelModel = (DefaultTableModel) tblTransaksi.getModel();
        tabelModel.addRow(new Object[]{transaksiDetail.getMakananId(),
            tipeMakananModel.getNama(),
            tipeMakananModel.getHarga(),
            transaksiDetail.getJumlah(),
            tipeMakananModel.getHarga() * transaksiDetail.getJumlah()
        });
        
        sumTotal(tipeMakananModel.getHarga() * transaksiDetail.getJumlah());
    }//GEN-LAST:event_btnTambahLaukActionPerformed

    private void btnTambahMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahMakananActionPerformed
        // TODO add your handling code here:
        Makanan tipeMakananModel = (Makanan) cmbMakanan.getSelectedItem();
        
        TransaksiDetail transaksiDetail = new TransaksiDetail();
        transaksiDetail.setMakananId(tipeMakananModel.getId());
        transaksiDetail.setJumlah(Integer.parseInt(spnMakanan.getValue().toString()));
        
        listDetailTransaksi = new ArrayList<>();
        listDetailTransaksi.add(transaksiDetail);
        
        tabelModel = (DefaultTableModel) tblTransaksi.getModel();
        tabelModel.addRow(new Object[]{transaksiDetail.getMakananId(),
            tipeMakananModel.getNama(),
            tipeMakananModel.getHarga(),
            transaksiDetail.getJumlah(),
            tipeMakananModel.getHarga() * transaksiDetail.getJumlah()
        });
        
        sumTotal(tipeMakananModel.getHarga() * transaksiDetail.getJumlah());
    }//GEN-LAST:event_btnTambahMakananActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        int bayar = Integer.parseInt(txtBayar.getText());
        int total = Integer.parseInt(txtTotal.getText());
        int kembali = bayar - total;

        txtKembali.setText(Integer.toString(kembali));
    }//GEN-LAST:event_btnBayarActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int baris = tblTransaksi.getSelectedRow();
        
        if (baris >= 0) {
            total = total - Integer.parseInt(tabelModel.getValueAt(baris, 4).toString());
            
            txtTotal.setText(Integer.toString(total));
            tabelModel.removeRow(baris);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        Transaksi transaksi = new Transaksi();
        transaksi.setNoTransaksi(txtNoTransaksi.getText());
        transaksi.setUserId(Integer.parseInt(UserSession.getUserId()));
        
        int count = tabelModel.getRowCount();
        
        for (int i = 0; i < count; i++) {
            TransaksiDetail transaksiDetail = new TransaksiDetail();
            transaksiDetail.setMakananId((Integer) tabelModel.getValueAt(i, 0));
            transaksiDetail.setJumlah((Integer) tabelModel.getValueAt(i, 4));
            transaksi.addTransaksiDetail(transaksiDetail);
        }
        
        if (updSQLFlag == false) {
            transaksiInterface.simpanTransaksi(transaksi);
            clearForm();
            initNoTransaksi();
        }
    }//GEN-LAST:event_btnSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambahLauk;
    private javax.swing.JButton btnTambahMakanan;
    private javax.swing.JButton btnTambahMinuman;
    private javax.swing.JComboBox cmbLauk;
    private javax.swing.JComboBox cmbMakanan;
    private javax.swing.JComboBox cmbMinuman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JSpinner spnLauk;
    private javax.swing.JSpinner spnMakanan;
    private javax.swing.JSpinner spnMinuman;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JFormattedTextField txtBayar;
    private javax.swing.JFormattedTextField txtKembali;
    private javax.swing.JTextField txtNoTransaksi;
    private javax.swing.JFormattedTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
